### ISSUE TITLE
Bug: 中文路径下使用 Koishi Desktop 无法安装插件

### ISSUE THREAD

**Issue by yujiewn** [koishijs/koishi-desktop#103]
### Describe the bug

在koishi控制台上无法进行插件安装

### Steps to reproduce

打开控制台，点击插件市场，点击安装显示安装失败

### Expected behavior

希望能安装插件

### Screenshots

![QQ图片20221018134431](https://user-images.githubusercontent.com/115611497/196345505-a40e2f25-0428-4f9b-b19d-991171a904e9.jpg)

### Versions

- OS: windows 10
- Platform: Discord
- Node version: 
- Koishi version: 4.9.5

**Comment by ilharp** [comment]
Caused by https://github.com/yarnpkg/berry/issues/5319. Cannot fix from Koishi Desktop or Yarn side.

**Comment by ilharp** [comment]
A new solution has been planned. Development work may start on `v0.10.x`.
