### ISSUE TITLE
Bug: 命令行窗口的标题会被一些 koishi 插件修改

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-desktop#112]
koishi 的 gocq 插件会将 koishi-desktop 命令行窗口的标题修改。

![image](https://user-images.githubusercontent.com/96647698/235222286-5dc4e2ee-3a9d-46fb-9194-0ddcca654b36.png)

**Comment by shigma** [comment]
duplicate of https://github.com/koishijs/koishi/issues/1037

然而我并不知道如何修复此问题，如果你感兴趣可以研究一下。随时欢迎 PR。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by idanran** [comment]
> Koishi Desktop 在运行时不会有终端显示。检查你是否将 Windows Terminal 作为了默认终端。如果是，你需要将默认终端修改为 conhost。

我确实将 Windows Terminal作为默认终端。

**Comment by ilharp** [comment]
我们仍在考虑等待上游（Windows Terminal）解决此问题，还是我们通过强制启动 conhost 的方法解决此问题。

鉴于 Windows Terminal 已成为 Windows 11 的默认终端，而 Windows Terminal 侧对此问题的态度不积极，我们可能会在未来版本强制使用 conhost。届时本 issue 将可以被解决。

Related：

https://github.com/koishijs/koishi-desktop/issues/63#issuecomment-1279802746

**Comment by idanran** [comment]
> 我们仍在考虑等待上游（Windows Terminal）解决此问题，还是我们通过强制启动 conhost 的方法解决此问题。
> 
> 鉴于 Windows Terminal 已成为 Windows 11 的默认终端，而 Windows Terminal 侧对此问题的态度不积极，我们可能会在未来版本强制使用 conhost。届时本 issue 将可以被解决。
> 
> Related：
> 
> https://github.com/koishijs/koishi-desktop/issues/63#issuecomment-1279802746
> 

嗯呐

**Comment by shigma** [comment]
这个 issue 的标题本身应该是由于 Koishi 的 issue 导致的。虽然 https://github.com/koishijs/koishi-desktop/issues/63#issuecomment-1279802746 让它得以显现了。

**Comment by ilharp** [comment]
我个人希望把此 issue可持续宝宝宝宝宝宝宝宝宝宝宝宝宝宝宝宝的态度你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好和你好你好你好你好你好你好和你好你好和你好你好你好你好你好你好你好你好你好和你好和你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好和你好你好你好你好你好你好你好你好你好男孩女孩她她她她她她她她她她她她她她她

**Comment by idanran** [comment]
> 这个 issue 的标题本身应该是由于 Koishi 的 issue 导致的。虽然 https://github.com/koishijs/koishi-desktop/issues/63#issuecomment-1279802746 让它得以显现了。

不知道有没有方法可以限制 gocq 子进程的行为。

**Comment by shigma** [comment]
https://support.github.com/contact/report-abuse?category=report-content&report=ilharp&report_content_url=https%3A%2F%2Fgithub.com%2Fkoishijs%2Fkoishi-desktop%2Fissues%2F112%23issuecomment-1527941734&report_id=20179549&report_type=content

**Comment by shigma** [comment]
> > 这个 issue 的标题本身应该是由于 Koishi 的 issue 导致的。虽然 [#63 (comment)](https://github.com/koishijs/koishi-desktop/issues/63#issuecomment-1279802746) 让它得以显现了。
> 
> 不知道有没有方法可以限制 gocq 子进程的行为。

这个问题来 https://github.com/koishijs/koishi/issues/1037 继续讨论吧。

**Comment by MaikoTan** [comment]
Since `go-cqhttp` and related plugins are not maintained anymore, this issue was obsolete.
