### ISSUE TITLE
在使用更新全部依赖后，无法正常运行

### ISSUE THREAD

**Issue by 502milk** [koishijs/koishi-desktop#113]
![image](https://github.com/koishijs/koishi-desktop/assets/49502047/f6f57732-105b-442a-abb1-4227609eb9c7)
[https://paste.ubuntu.com/p/C3DZR5VK2B/](https://paste.ubuntu.com/p/C3DZR5VK2B/)
系统win11 本版 Koishi 桌面 v0.10.4

**Comment by 502milk** [comment]
以确定，在控制台内更新到koishi4.12.9就会引起bug

**Comment by shigma** [comment]
应该是 @koishijs/plugin-console 的 bug。感谢反馈，我们会以最快速度修复。

**Comment by 502milk** [comment]
> 

那么...我现在要怎么给他修回来呢·-·

**Comment by shigma** [comment]
```
koi yarn -n default add @koishijs/plugin-console@latest
```

**Comment by 502milk** [comment]
> ```
> koi yarn -n default add @koishijs/plugin-console@latest
> ```

`0000|3|2023-05-21 17:19: [D] launcher 触发操作：yarn
0000|3|2023-05-21 17:19: [D] launcher 触发操作：运行服务
0000|3|2023-05-21 17:19: [D] launcher Writing daemon.lock...
0000|3|2023-05-21 17:19: [D] launcher Serving daemon...
0000|3|2023-05-21 17:19: [D] launcher Client connected at 127.0.0.1:55904
0000|3|2023-05-21 17:19: [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:19: [D] launcher Send pong back
0000|3|2023-05-21 17:19: [D] launcher Client connected at 127.0.0.1:55905
0000|3|2023-05-21 17:19: [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:19: [D] launcher Acquired task 1
0000|3|2023-05-21 17:19: [D] launcher Parsed command: yarn
0001|3|2023-05-21 17:19: [D] launcher Trigger KoiCmd yarn
0001|2|2023-05-21 17:19: [I] launcher Running command:
                        []string{"add", "@koishijs/plugin-console@latest"}
                        On instance: default
2000|2|➤ YN0000: ┌ Resolution step
2000|2|➤ YN0060: │ @koishijs/boilerplate@workspace:. provides koishi (pc6ab0) with version 4.12.8, which doesn't satisfy what @koishijs/plugin-console requests
2000|2|➤ YN0002: │ @koishijs/plugin-adapter-discord@npm:3.6.1 [dd020] doesn't provide @satorijs/satori (p52e84), requested by @satorijs/adapter-discord
2000|2|➤ YN0002: │ @koishijs/plugin-adapter-kook@npm:3.8.2 [dd020] doesn't provide @satorijs/satori (p9fb), requested by @satorijs/adapter-kook
2000|2|➤ YN0002: │ @koishijs/plugin-adapter-lark@npm:2.0.2 [dd020] doesn't provide @satorijs/satori (p761fd), requested by @satorijs/adapter-lark
2000|2|➤ YN0002: │ @koishijs/plugin-adapter-onebot@npm:5.7.1 [dd020] doesn't provide @satorijs/satori (pb4899), requested by @satorijs/adapter-onebot
2000|2|➤ YN0002: │ @koishijs/plugin-adapter-telegram@npm:3.7.8 [dd020] doesn't provide @satorijs/satori (p145de), requested by @satorijs/adapter-telegram
2000|2|➤ YN0002: │ @koishijs/plugin-database-sqlite@npm:3.4.4 [dd020] doesn't provide @minatojs/core (pcad61), requested by @minatojs/driver-sqlite
2000|2|➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
2000|2|➤ YN0000: └ Completed
2000|2|➤ YN0000: ┌ Fetch step
2000|2|➤ YN0000: └ Completed
2000|2|➤ YN0000: ┌ Link step
2000|2|➤ YN0000: └ Completed
2000|2|➤ YN0000: Done with warnings in 0s s
0000|3|2023-05-21 17:19: [D] launcher Releasing task 1
0000|3|2023-05-21 17:20:00 [D] launcher 触发操作：运行
0000|3|2023-05-21 17:20:00 [D] launcher 触发操作：运行用户界面
0000|3|2023-05-21 17:20:00 [D] launcher Writing tray.lock...
0000|3|2023-05-21 17:20:00 [D] launcher 托盘已就绪。
0000|3|2023-05-21 17:20:00 [D] launcher Client connected at 127.0.0.1:55923
0000|3|2023-05-21 17:20:00 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:00 [D] launcher Send pong back
0000|3|2023-05-21 17:20:00 [D] launcher Client connected at 127.0.0.1:55924
0000|3|2023-05-21 17:20:00 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:00 [D] launcher Send pong back
0000|3|2023-05-21 17:20:00 [D] launcher Client connected at 127.0.0.1:55925
0000|3|2023-05-21 17:20:00 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:00 [D] launcher Parsed command: ps
0000|3|2023-05-21 17:20:00 [D] launcher Acquired task 2
0002|3|2023-05-21 17:20:00 [D] launcher Trigger KoiCmd ps
0000|3|2023-05-21 17:20:00 [D] launcher Releasing task 2
0000|3|2023-05-21 17:20:05 [D] launcher 正在启动实例 default
0000|3|2023-05-21 17:20:05 [D] launcher Client connected at 127.0.0.1:559
0000|3|2023-05-21 17:20:05 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:05 [D] launcher Send pong back
0000|3|2023-05-21 17:20:05 [D] launcher Client connected at 127.0.0.1:559
0000|3|2023-05-21 17:20:05 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:05 [D] launcher Parsed command: start
0000|3|2023-05-21 17:20:05 [D] launcher Acquired task 3
0003|3|2023-05-21 17:20:05 [D] launcher Trigger KoiCmd start
0003|2|2023-05-21 17:20:05 [I] launcher Starting instance default...
0000|3|2023-05-21 17:20:05 [D] launcher Releasing task 3
1000|2|2023-05-21 17:20:06 [I] app Koishi/4.12.8
1000|2|2023-05-21 17:20:06 [I] app apply plugin group:entry
1000|2|2023-05-21 17:20:06 [I] app apply plugin group:basic
1000|2|2023-05-21 17:20:06 [I] app apply plugin bind
1000|2|2023-05-21 17:20:06 [I] app apply plugin commands
1000|2|2023-05-21 17:20:06 [I] app apply plugin help
1000|2|2023-05-21 17:20:06 [I] app apply plugin locales
1000|2|2023-05-21 17:20:06 [I] app apply plugin rate-limit
1000|2|2023-05-21 17:20:06 [I] app apply plugin group:console
1000|2|2023-05-21 17:20:06 [I] app apply plugin analytics
1000|2|2023-05-21 17:20:06 [I] app apply plugin console
1000|2|2023-05-21 17:20:06 [I] app apply plugin dataview
1000|2|2023-05-21 17:20:06 [I] app apply plugin desktop
1000|2|2023-05-21 17:20:06 [I] app apply plugin explorer
1000|2|2023-05-21 17:20:06 [I] app apply plugin logger
1000|2|2023-05-21 17:20:06 [I] app apply plugin insight
1000|2|2023-05-21 17:20:06 [I] app apply plugin market
1000|2|2023-05-21 17:20:06 [I] app apply plugin sandbox
1000|2|2023-05-21 17:20:06 [I] app apply plugin status
1000|2|2023-05-21 17:20:06 [I] app apply plugin group:storage
1000|2|2023-05-21 17:20:06 [I] app apply plugin database-sqlite
1000|2|2023-05-21 17:20:06 [I] app apply plugin assets-local
1000|2|2023-05-21 17:20:06 [I] app apply plugin group:adapter
1000|2|2023-05-21 17:20:06 [I] app apply plugin adapter-onebot
1000|2|2023-05-21 17:20:06 [I] app apply plugin gocqhttp
1000|2|2023-05-21 17:20:06 [I] assets missing config "selfUrl", fallback to "file:" scheme
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-commands\lib\index.js::29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-locales\lib\index.js::29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-analytics\lib\index.js::29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at NodeLoader.forkPlugin (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\loader\lib\shared.js:189:)
1000|2|                            at NodeLoader.resolvePlugin (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\loader\lib\index.js:94:45)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-dataview\lib\index.cjs:29:29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-explorer\lib\index.cjs::29)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-logger\lib\index.js:27:29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-insight\lib\index.cjs:28:29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-market\lib\node\index.js:47:29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-sandbox\lib\index.js::29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-status\lib\index.js:46:29)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:216:6
1000|2|2023-05-21 17:20:06 [W] app TypeError: import_koishi.Schema.object(...).i18n is not a function
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\@koishijs\plugin-console\lib\node\index.js:219:3)
1000|2|                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
1000|2|                            at Module.load (node:internal/modules/cjs/loader:1069:)
1000|2|                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
1000|2|                            at Module.require (node:internal/modules/cjs/loader:1093:19)
1000|2|                            at Object.<anonymous> (E:\Bot\koishi-desktop\data\instances\default\node_modules\koishi-plugin-gocqhttp\lib\index.js:8:26)
1000|2|                            at require (node:internal/modules/cjs/helpers:108:18)
1000|2|                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
1000|2|2023-05-21 17:20:06 [I] app server listening at http://0.0.0.0:5140
0002|3|2023-05-21 17:20:06 [D] launcher 已解析到 http://0.0.0.0:5140。
0000|3|2023-05-21 17:20:07 [D] launcher 正在重建托盘
0000|3|2023-05-21 17:20:07 [D] launcher Client connected at 127.0.0.1:559
0000|3|2023-05-21 17:20:07 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:07 [D] launcher Send pong back
0000|3|2023-05-21 17:20:07 [D] launcher Client connected at 127.0.0.1:559
0000|3|2023-05-21 17:20:07 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:07 [D] launcher Parsed command: ps
0000|3|2023-05-21 17:20:07 [D] launcher Acquired task 4
0004|3|2023-05-21 17:20:07 [D] launcher Trigger KoiCmd ps
0000|3|2023-05-21 17:20:07 [D] launcher Releasing task 4
0000|3|2023-05-21 17:20:15 [D] launcher 正在打开实例 default
0000|3|2023-05-21 17:20:15 [D] launcher Client connected at 127.0.0.1:55951
0000|3|2023-05-21 17:20:15 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:15 [D] launcher Send pong back
0000|3|2023-05-21 17:20:15 [D] launcher Client connected at 127.0.0.1:55952
0000|3|2023-05-21 17:20:15 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:15 [D] launcher Parsed command: open
0000|3|2023-05-21 17:20:15 [D] launcher Acquired task 5
0005|2|2023-05-21 17:20:15 [I] launcher Opening instance default...
0005|3|2023-05-21 17:20:15 [D] launcher Trigger KoiCmd open
0005|3|2023-05-21 17:20:15 [D] launcher Running webview for instance default: 
0005|3|2023-05-21 17:20:15 [D] launcher Starting KoiShell process.
                        arg: map[string]string{"mode":"webview", "name":"default", "url":""}
                        argJson: {"mode":"webview","name":"default","url":""}
                        argB64: eyJtb2RlIjoid2VidmlldyIsIm5hbWUiOiJkZWZhdWx0IiwidXJsIjoiIn0=
0000|3|2023-05-21 17:20:15 [D] launcher Releasing task 5
0000|3|2023-05-21 17:20:17 [D] launcher 正在重建托盘
0000|3|2023-05-21 17:20:17 [D] launcher Client connected at 127.0.0.1:55953
0000|3|2023-05-21 17:20:17 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:17 [D] launcher Send pong back
0000|3|2023-05-21 17:20:17 [D] launcher Client connected at 127.0.0.1:55954
0000|3|2023-05-21 17:20:17 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:17 [D] launcher Parsed command: ps
0000|3|2023-05-21 17:20:17 [D] launcher Acquired task 6
0006|3|2023-05-21 17:20:17 [D] launcher Trigger KoiCmd ps
0000|3|2023-05-21 17:20:17 [D] launcher Releasing task 6
0005|3|2023-05-21 17:20: [D] launcher KoiShell successfully exited.
0000|3|2023-05-21 17:20:40 [D] launcher 正在打开实例 default
0000|3|2023-05-21 17:20:40 [D] launcher Client connected at 127.0.0.1:55975
0000|3|2023-05-21 17:20:40 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:20:40 [D] launcher Send pong back
0000|3|2023-05-21 17:20:40 [D] launcher Client connected at 127.0.0.1:55976
0000|3|2023-05-21 17:20:40 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:20:40 [D] launcher Parsed command: open
0007|3|2023-05-21 17:20:40 [D] launcher Trigger KoiCmd open
0000|3|2023-05-21 17:20:40 [D] launcher Acquired task 7
0007|2|2023-05-21 17:20:40 [I] launcher Opening instance default...
0007|3|2023-05-21 17:20:40 [D] launcher Running webview for instance default: 
0005|3|2023-05-21 17:20:40 [D] launcher Starting KoiShell process.
                        arg: map[string]string{"mode":"webview", "name":"default", "url":""}
                        argJson: {"mode":"webview","name":"default","url":""}
                        argB64: eyJtb2RlIjoid2VidmlldyIsIm5hbWUiOiJkZWZhdWx0IiwidXJsIjoiIn0=
0000|3|2023-05-21 17:21:10 [D] launcher 正在重启实例 default
0000|3|2023-05-21 17:21:10 [D] launcher Client connected at 127.0.0.1:56079
0000|3|2023-05-21 17:21:10 [D] launcher Parsed request type: ping
0000|3|2023-05-21 17:21:10 [D] launcher Send pong back
0000|3|2023-05-21 17:21:10 [D] launcher Client connected at 127.0.0.1:56080
0000|3|2023-05-21 17:21:10 [D] launcher Parsed request type: cmd
0000|3|2023-05-21 17:21:10 [D] launcher Parsed command: restart
0000|3|2023-05-21 17:21:10 [D] launcher Acquired task 8
0008|3|2023-05-21 17:21:10 [D] launcher Trigger KoiCmd restart
0008|2|2023-05-21 17:21:10 [I] launcher Stopping instance default...
0002|2|2023-05-21 17:21:10 [W] launcher Instance default exited with: exit status 0xc000013a.
0008|2|2023-05-21 17:21:12 [I] launcher Starting instance default...
0000|3|2023-05-21 17:21:12 [D] launcher Releasing task 80000|1|2023-05-21 17:21:12 [E] launcher koi: internal error: instance already started

`
看来不行·-·

**Comment by shigma** [comment]
额，你为啥连 Koishi 也没有更新……

koi yarn -n default add koishi@latest

**Comment by 502milk** [comment]
不知道·-·
但现在能跑了

**Comment by shigma** [comment]
能解决就好~
