### ISSUE TITLE
更新版本后出现的bug

### ISSUE THREAD

**Issue by Mrqqeat** [koishijs/koishi-desktop#115]
更新后，启动，启动后没报错，打开5140网页后报错如下，显示的页面是空白的

index.ts?v=19e370bb:15 Uncaught TypeError: Cannot read properties of undefined (reading 'provide')
    at index.ts?v=19e370bb:15

那一行是root.app.provide('ecTheme', 'dark-blue')报错

**Comment by ilharp** [comment]
你是否未在一次更新操作内更新所有依赖到最新版本？请参阅下面的帖子了解更多信息：

https://forum.koishi.xyz/t/topic/829

**Comment by Mrqqeat** [comment]
> 你是否未在一次更新操作内更新所有依赖到最新版本？请参阅下面的帖子了解更多信息：
> 
> https://forum.koishi.xyz/t/topic/829

对，因为看到有些包的版本是红色的点，以为要先更新了指定的包后才能更新这些...
不过我还原后将全部的包都点到最新版本，点右上角对钩更新完成后，重新打开页面还是有报错
Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n'
index.js?import:formatted:2 Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n'

然后点击账号->登录没反应

**Comment by ilharp** [comment]
> 不过我还原后将全部的包都点到最新版本，点右上角对钩更新完成后，重新打开页面还是有报错 Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n' index.js?import:formatted:2 Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n'

该报错是正常的，不影响使用。

> 然后点击账号->登录按钮没反应

登录按钮指的是 auth 或 login 插件的登录功能吗？如果你无法使用账号密码登录的话，可以临时使用平台登录的方式登录。

**Comment by Mrqqeat** [comment]
> 

我选择[平台账户登录]点击获取验证码，没有反应，控制台也没输出。
选择[用户密码登录]点击登录按钮，也是没有反应，控制台也没有输出。
应该不是网络问题，因为在更新前是可以登陆的

**Comment by Mrqqeat** [comment]
> > 不过我还原后将全部的包都点到最新版本，点右上角对钩更新完成后，重新打开页面还是有报错 Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n' index.js?import:formatted:2 Uncaught (in promise) SyntaxError: The requested module '/vite/@fs/root/koishi-app-99/.vite/deps/@koishijs_client.js?v=78a50c3b' does not provide an export named 'useI18n'
> 
> 该报错是正常的，不影响使用。
> 
> > 然后点击账号->登录按钮没反应
> 
> 登录按钮指的是 auth 或 login 插件的登录功能吗？如果你无法使用账号密码登录的话，可以临时使用平台登录的方式登录。

我选择[平台账户登录]点击获取验证码，没有反应，控制台也没输出。
选择[用户密码登录]点击登录按钮，也是没有反应，控制台也没有输出。
应该不是网络问题，因为在更新前是可以登陆的

**Comment by ilharp** [comment]
如果你仍在使用 login 插件，则可能需要更换至最新的 `@koishijs/plugin-auth` 插件，该插件提供了最新的登录逻辑。

如果你现在无法登录控制台，则可以先手动修改 `koishi.yml`，临时停用相关插件后重启 Koishi 进行配置。

**Comment by Mrqqeat** [comment]
> @koishijs/plugin-auth

我npm i @koishijs/plugin-auth 安装了一下不行，如果修改koishi.yml，要临时停用登录吗，要如何停用呢

**Comment by ilharp** [comment]
如果你使用 npm 进行包管理，那么这个问题不属于 Koishi Desktop，请前往对应的项目提交问题。

如果你使用 Koishi Desktop，临时停用插件的方法可以参考下面的帖子：

https://forum.koishi.xyz/t/topic/296
