### ISSUE TITLE
Bug: 以非管理员模式启动后报错

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-desktop#116]
```
0000|2023-05-27 00:08:01 [I] launcher Koishi Desktop v0.10.5
0000|2023-05-27 00:08:01 [W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.
```

以管理员模式启动后，提示以上信息的窗口不再展现。

koishi-desktop-win-x64-v0.10.5.msi

**Comment by ilharp** [comment]
我没有看到任何报错。你说的报错在哪里？

另外，Koishi Desktop 被设计为在普通用户权限下正常运行，使用管理员模式启动是错误的做法。请不要使用管理员模式启动 Koishi Desktop。

**Comment by idanran** [comment]
> ```
> 0000|2023-05-27 00:08:01 [W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.
> ```

```
0000|2023-05-27 00:08:01 [W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.
```

**Comment by idanran** [comment]
> 我没有看到任何报错。你说的报错在哪里？
> 
> 另外，Koishi Desktop 被设计为在普通用户权限下正常运行，使用管理员模式启动是错误的做法。请不要使用管理员模式启动 Koishi Desktop。

```[W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.```

**Comment by ilharp** [comment]
> > 我没有看到任何报错。你说的报错在哪里？
> > 另外，Koishi Desktop 被设计为在普通用户权限下正常运行，使用管理员模式启动是错误的做法。请不要使用管理员模式启动 Koishi Desktop。
> 
> `[W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.`

你应该看到了该条日志开头的 `[W]` 标识，这表明这条日志是一个警告。警告不是错误，并且是预期的行为。Koishi 和 Koishi Desktop 在每次启动时均会打印若干条警告，这是正常现象，并不表明程序的运行出现了问题。

我们仍在评估该条日志应该以信息（`[I]`）还是警告（`[W]`）的方式进行打印。如果你确实认为该条日志的打印给你带来了误解的话可以提出。

**Comment by idanran** [comment]
> > > 我没有看到任何报错。你说的报错在哪里？
> > > 另外，Koishi Desktop 被设计为在普通用户权限下正常运行，使用管理员模式启动是错误的做法。请不要使用管理员模式启动 Koishi Desktop。
> > 
> > 
> > `[W] launcher failed to chmod data folder bin: chmod C:\Program Files\Koishi\Desktop\bin: Access is denied.`
> 
> 你应该看到了该条日志开头的 `[W]` 标识，这表明这条日志是一个警告。警告不是错误，并且是预期的行为。Koishi 和 Koishi Desktop 在每次启动时均会打印若干条警告，这是正常现象，并不表明程序的运行出现了问题。
> 
> 我们仍在评估该条日志应该以信息（`[I]`）还是警告（`[W]`）的方式进行打印。如果你确实认为该条日志的打印给你带来了误解的话可以提出。

嗯呐
