### ISSUE TITLE
Feature: 鼠标左键点击托盘图标时直接打开 Webview

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-desktop#117]
![image](https://github.com/koishijs/koishi-desktop/assets/96647698/a03fd9f3-f636-463e-bd0b-917f217ea40b)

**Comment by ilharp** [comment]
[多实例](https://koishi.chat/zh-CN/manual/recipe/multiple.html#%E5%A4%9A%E5%AE%9E%E4%BE%8B) 是 Koishi 的一个常见的使用方法，很多用户在使用 Koishi 时会同时使用多个实例，每个实例都有单独的控制台地址和窗口。此种情况下左键单击仍然需要打开一个菜单以供选择。

此外自定义单击行为也是上游依赖的一个尚未实现的功能（上游目前仅支持左右键打开相同的菜单），因此目前无法实现。

**Comment by idanran** [comment]
> [多实例](https://koishi.chat/zh-CN/manual/recipe/multiple.html#%E5%A4%9A%E5%AE%9E%E4%BE%8B) 是 Koishi 的一个常见的使用方法，很多用户在使用 Koishi 时会同时使用多个实例，每个实例都有单独的控制台地址和窗口。此种情况下左键单击仍然需要打开一个菜单以供选择。
> 
> 此外自定义单击行为也是上游依赖的一个尚未实现的功能（上游目前仅支持左右键打开相同的菜单），因此目前无法实现。
> 

嗷

**Comment by idanran** [comment]
> [多实例](https://koishi.chat/zh-CN/manual/recipe/multiple.html#%E5%A4%9A%E5%AE%9E%E4%BE%8B) 是 Koishi 的一个常见的使用方法，很多用户在使用 Koishi 时会同时使用多个实例，每个实例都有单独的控制台地址和窗口。此种情况下左键单击仍然需要打开一个菜单以供选择。
> 
> 此外自定义单击行为也是上游依赖的一个尚未实现的功能（上游目前仅支持左右键打开相同的菜单），因此目前无法实现。
> 

嗷

**Comment by Anillc** [comment]
关于这个问题，其实在一些平台上还会有一些问题，比如说在 gnome 环境下点击托盘图标会打开通过系统 api 注册的菜单，但是如果是程序自定义的点击行为就会失效。
