### ISSUE TITLE
Bug: 找不到msvcp140.dll等问题

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/koishi-desktop#120]
该问题由于缺少相关的vc++库导致，可能会出现打开不了窗口的问题，自行下载相关依赖库安装即可

> 可以使用的链接(64位Windows): https://download.visualstudio.microsoft.com/download/pr/b929b7fe-5c89-4553-9abe-6324631dcc3a/296F96CD102250636BCD23AB6E6CF70935337B1BBB3507FE8521D8D9CFAA932F/VC_redist.x64.exe

**Comment by ilharp** [comment]
正确的链接是 <https://aka.ms/vs/17/release/vc_redist.x64.exe>。此问题已在 v0.10.5 中修复并在 v0.10.6 中回退。

v0.10.5 被回退的原因是在安装 Koishi 时同时安装所有依赖可能会造成对用户系统本身的变更，我们仍在评估此行为的必要性。如果此变更合理，后续版本中会重新附带。
