### ISSUE TITLE
Feature: 当实例的 yarn.lock 的 `__metadata.version` 小于 `8` 时, 自动执行一次 `yarn install`

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-desktop#124]
可解决以下问题
```
1000|2|Internal Error: @koishijs/boilerplate@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
1000|2|    at Bd.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:141:1488)
1000|2|    at $x.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:205:84)
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7182
1000|2|    at Yy (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:140:5)
1000|2|    at ne (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7162)
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7788
```

**Comment by ilharp** [comment]
Koishi Desktop v1 内置 Yarn v4.0.1。什么样的情况下会出现这样的问题？

**Comment by idanran** [comment]
> Koishi Desktop v1 内置 Yarn v4.0.1。什么样的情况下会出现这样的问题？

从 0.10.7 更新到 1.0.0，因为以前是 Yarn v3

**Comment by ilharp** [comment]
Koishi Desktop v1 不兼容 Koishi Desktop v0。

[v1.0.0 的发行说明](https://github.com/koishijs/koishi-desktop/releases/tag/v1.0.0) 中已经包含了迁移指南，v0.2.0 以上的所有版本都可以使用 `koi yarn -n <实例名> set version berry && koi yarn -n <实例名>` 手动迁移。

同时，此问题已在论坛开贴： <https://k.ilharp.cc/6103> ，方便用户在遇到此问题时在论坛搜索。

**Comment by idanran** [comment]
> Koishi Desktop v1 不兼容 Koishi Desktop v0。
> 
> [v1.0.0 的发行说明](https://github.com/koishijs/koishi-desktop/releases/tag/v1.0.0) 中已经包含了迁移指南，v0.2.0 以上的所有版本都可以使用 `koi yarn -n <实例名> set version berry && koi yarn -n <实例名>` 手动迁移。
> 
> 同时，此问题已在论坛开贴： <https://k.ilharp.cc/6103> ，方便用户在遇到此问题时在论坛搜索。
> 

https://yarnpkg.com/getting-started/install

文档里是 `yarn set version stable`

**Comment by ilharp** [comment]
latest、berry 和 stable 三个词作用相同。 <https://yarnpkg.com/cli/set/version>

**Comment by idanran** [comment]
> latest、berry 和 stable 三个词作用相同。 <https://yarnpkg.com/cli/set/version>
> 

原来如此
