### ISSUE TITLE
发布构建到 sourceforge

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-desktop#125]

**Comment by ilharp** [comment]
SourceForge 在海外的下载速度慢于 GitHub，在国内的下载速度慢于 AppCenter。

另见：

[Why GitHub and not Sourceforge? - Reddit](https://www.reddit.com/r/programming/comments/9bk4r)

**Comment by idanran** [comment]
> SourceForge 在海外的下载速度慢于 GitHub，在国内的下载速度慢于 AppCenter。
> 
> 另见：
> 
> [Why GitHub and not Sourceforge? - Reddit](https://www.reddit.com/r/programming/comments/9bk4r)

https://install.appcenter.ms/orgs/koishi/apps/koishi-desktop-for-windows/distribution_groups/stable

以上页面（AppCenter）在国内网络环境下，无缓存的时候加载时长超过 3 分钟。

![image](https://github.com/koishijs/koishi-desktop/assets/96647698/abfb2244-89c3-4997-958b-1d472807b2b0)

**Comment by ilharp** [comment]
1.

![image](https://github.com/koishijs/koishi-desktop/assets/20179549/97d5ae54-937e-4969-aee8-5383b55e75eb)

我这里加载不会超过 8 秒。

---

2.

即使除去网络原因，SourceForge 还有太多根本无法使用的地方，上面的帖子已有具体讨论。大部分普通用户甚至找不到如何在 SourceForge 中下载文件。

---

3.

Koishi 普遍使用「同源下载」策略。如果你的网络无法连接到 Azure，那么即使你能够在别的网站下载到 Koishi，安装 Koishi 时你也会因为无法连接到 Azure 导致 Edge WebView2 安装失败，进而使整个 Koishi 安装失败。

不在论坛设立 Koishi 的安装链接也是出于相同原因。如果你因为打不开 Koishi 官网而在其他地方下载 Koishi，那么安装 Koishi 以后你将会因为无法连接到插件市场而无法下载任何插件。绕开 AppCenter 或绕开 Koishi 官网都是没有意义的。
