### ISSUE TITLE
koishi无法启动bug

### ISSUE THREAD

**Issue by kafuuchinolpx** [koishijs/koishi-desktop#128]
在Windows server启动koishi失败，服务器重启后出现图中情况，无法启动
![af3aaea2-5cbe-45a5-b91a-fdc2ecb74aef](https://github.com/koishijs/koishi-desktop/assets/46470388/54c68983-9df6-4ace-9405-004cf67bbbfa)

**Comment by ilharp** [comment]
重启即可

**Comment by huvz04** [comment]
系统：Windows Server 2022 Standard 21H2, 
CPU：Intel 8085
内存：16G
出现了同样的情况。第一次安装可以显示页面。重启应用后无法显示窗口。只有右下角icon显示
![图片](https://github.com/koishijs/koishi-desktop/assets/91484306/405581f4-5f91-4f55-b886-0e989dad3ff3)

重装后仍然无法解决。发现C:\Users\Administrator\AppData\Roaming\Koishi下的文件不会被删除。清理该目录后，重新安装即可解决页面不渲染。猜测是之前升级了部分依赖的问题。

**Comment by ilharp** [comment]
> 只有右下角icon显示

你这个跟楼主是完全不一样的情况……你自己也说了右下角 icon 有显示，而楼主没有显示。

只升级部分依赖导致的 Koishi 无法启动是很常见的问题，双清即可。楼主的问题只需重启即可，不需要重装或清除数据。

**Comment by ilharp** [comment]
> 第二次打开后提示Koishi is already running

你右下角已经显示 Koishi 图标了，Koishi 确实正在 running，是预期行为。没有启动窗口则是因为升级依赖过程出错，按照你所说的双清方法即可正常解决。

**Comment by kafuuchinolpx** [comment]
> 重启即可

重启服务器和重装都没有效果，打开依旧提示在运行，但任务管理器和右下角都没有koishi的相关任务

**Comment by ilharp** [comment]
这个是偶发的一个 bug。打开文件资源管理器，在地址栏中粘贴 `%APPDATA%\Koishi\Desktop\data\lock` 并回车，然后删掉文件夹里的所有文件，最后再次打开 Koishi 即可。无需重启系统。

**Comment by kafuuchinolpx** [comment]
> 这个是偶发的一个 bug。打开文件资源管理器，在地址栏中粘贴 `%APPDATA%\Koishi\Desktop\data\lock` 并回车，然后删掉文件夹里的所有文件，最后再次打开 Koishi 即可。无需重启系统。

好的，问题已经解决了，感谢
