### ISSUE TITLE
v0.6.0沒有win版嗎?

### ISSUE THREAD

**Issue by cherry0804** [koishijs/koishi-desktop#59]
Filelist有5項，Assets卻只有osx和linux版

**Comment by shigma** [comment]
我们会尽快修复，你可以先用 0.5.x 版本，没有功能上的差异。

**Comment by ilharp** [comment]
我们会在 2-3 小时内修复并发布 v0.6.1。推荐使用 [这里](https://github.com/koishijs/koishi-desktop/actions/runs/3202350549) 构建的 nightly 版本，0.5.x 现在存在一些问题（更新会清空数据），可以先使用 nightly 版本或等待几小时。

**Comment by cherry0804** [comment]
好的

**Comment by ilharp** [comment]
[v0.6.1](https://github.com/koishijs/koishi-desktop/releases/tag/v0.6.1) 已经发布。
