### ISSUE TITLE
Feature Request: MacOS 11.6 Support

### ISSUE THREAD

**Issue by Z-fly** [koishijs/koishi-desktop#74]
![image](https://user-images.githubusercontent.com/10470892/197091684-185a1f2d-7e16-4225-8a3c-319ae7bf91c0.png)

**Comment by ilharp** [comment]
已完成调研。支持 `macOS Big Sur 11` 的最高套件版本为 `Xcode 12.5.1 - Swift 5.4`。选择迁移到 `Xcode 13.2.1 - Swift 5.4`。

**Comment by shigma** [comment]
![7~7~DSY)0$7 WJJB)GQBL B](https://user-images.githubusercontent.com/33423008/197344018-b1d2b4da-f3b0-4043-90b7-b0957616ea29.png)

**Comment by ilharp** [comment]
😂

虽然我已经把工具链降级了，但由于 lockfile 还没更新，也没发版，所以我还没关这个 issue，结果你直接关了

但总之问题已经被修复了，下一个版本发布会带有 macOS 11 的支持的

**Comment by Z-fly** [comment]
我以为10.13到11都一样的工具链，那顺便问下10.15及以下是不能用吗？

**Comment by ilharp** [comment]
> 那顺便问下10.15及以下是不能用吗？

macOS 11 以下不能使用的原因是 Koishi Desktop 使用了 macOS 11 上的 AppKit API。

macOS 10.15 (Catalina) 已于一周前（12 Sep 2022）结束支持。我们不再考虑对其添加支持。如果你使用 macOS Catalina，我们推荐升级你的系统，或更换一台新的电脑。

**Comment by Z-fly** [comment]
ok.也就是说，如果11结束支持，那koishi也就不考虑11的兼容性了是吧

**Comment by ilharp** [comment]
Koishi Desktop 根据其目标的平台所属的组织或团体制定的产品生命周期确定其适配。Koishi 本体根据 [Node.js](https://nodejs.org) 的发布工作组制定的 [产品发布计划](https://github.com/nodejs/release) 确定其适配。但二者均不保证此适配具有完全的可靠性。如果你发现了我们适配工作中出现的 bug，可以在对应的存储库提交 issue。
