### ISSUE TITLE
Bug:在使用中文用户名的电脑上，无法正常运行koishi

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi-desktop#76]
环境：windows11，koishi-desktop-win-x64-v0.7.2.zip，中文用户名
现象：可以正常打开启动器，但没有弹出控制台网页，右下角中的实例时未启动状态
复现方法：[复现视频](http://gz.elchapo.cn:5244/local/koishi.mp4)
复现概率：100%

目前的临时解决方法是将解压后的整个文件夹移动到无中文路径进行运行，如D:/test/koishi
通过msi安装包进行安装的方法未测试，但是也有报告运行异常。

**Comment by MirrorCY** [comment]
#69

**Comment by ilharp** [comment]
Blocked by upstream issues:

- https://github.com/yarnpkg/berry/issues/3725
- https://github.com/yarnpkg/berry/issues/4448
- https://github.com/yarnpkg/berry/issues/4499
- https://github.com/yarnpkg/berry/issues/4837

**Comment by MirrorCY** [comment]
了解  感谢您的回复  期待更新

**Comment by H4M5TER** [comment]
7f69e99c4d4678d3288b0e8aebc51662555b3b52 fix this
