### ISSUE TITLE
bug: unable to start koishi-desktop-win-x64-v0.8.1 on windows11

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi-desktop#80]
[log 文件](http://gz.elchapo.cn:5244/local/1.txt)
复现步骤：
1. 全新安装 Windows11 虚拟机
2. （选择一个非中文用户名）
3. 安装 `koishi-desktop-win-x64-v0.8.1.msi`
4. 启动开始菜单中的 koishi

系统版本：Windows 11-10.0.22621

**Comment by MirrorCY** [comment]
#77

**Comment by MaikoTan** [comment]
> #77

Is it related or the same problem? Or just a reference?

------

它是关联的吗，还是同一个问题？或者只是引用？

**Comment by MirrorCY** [comment]
重启虚拟机后无法再次复现此问题，就此关闭。
