### ISSUE TITLE
macOS 无法启动

### ISSUE THREAD

**Issue by Z-fly** [koishijs/koishi-desktop#84]
![image](https://user-images.githubusercontent.com/10470892/206075258-7285beea-a999-42b3-8787-b6d9dc2fbb47.png)
日志如下：
```
0000|3|2022-12-07 10:44:05 [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-07 10:44:05 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:05 [D] launcher Trigger action: run
0000|3|2022-12-07 10:44:05 [D] launcher Trigger action: run ui
0000|3|2022-12-07 10:44:05 [D] launcher service gopkg.ilharper.com/koi/app/koicli/action.RunUi invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *tray.TrayDaemon injected
0000|3|2022-12-07 10:44:05 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *tray.TrayDaemon invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:05 [D] launcher Writing tray.lock...
0000|3|2022-12-07 10:44:05 [D] launcher service *tray.TrayUnlocker injected
0000|3|2022-12-07 10:44:05 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:05 [D] launcher Tray ready.
0000|3|2022-12-07 10:44:05 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-07 10:44:05 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-07 10:44:07 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher Trigger action: run daemon
0000|3|2022-12-07 10:44:07 [D] launcher service *daemonproc.DaemonProcess invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *daemonproc.DaemonProcess injected
0000|3|2022-12-07 10:44:07 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *logger.Logger invoked
0000|2|2022-12-07 10:44:07 [I] launcher Starting these instances:
                        default
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-07 10:44:07 [D] launcher service gopkg.ilharper.com/koi/app/util.AppVersion invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *daemonunlk.DaemonUnlocker injected
0000|2|2022-12-07 10:44:07 [W] launcher Instance default exited with: fork/exec /Users/z/Library/Application Support/Koishi/Desktop/data/node/bin/koishi: permission denied
0000|3|2022-12-07 10:44:07 [D] launcher Writing daemon.lock...
0000|3|2022-12-07 10:44:07 [D] launcher service *koicmd.Registry injected
0000|3|2022-12-07 10:44:07 [D] launcher service *daemonserv.DaemonService injected
0000|3|2022-12-07 10:44:07 [D] launcher service *daemonserv.DaemonService invoked
0000|3|2022-12-07 10:44:07 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:07 [D] launcher Serving daemon...
0000|3|2022-12-07 10:44:07 [D] launcher service *http.Server injected
0000|3|2022-12-07 10:44:11 [D] launcher Client connected at 127.0.0.1:62565
0000|3|2022-12-07 10:44:11 [D] launcher Parsed request type: ping
0000|3|2022-12-07 10:44:11 [D] launcher Send pong back
0000|3|2022-12-07 10:44:11 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:11 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:11 [D] launcher Client connected at 127.0.0.1:62566
0000|3|2022-12-07 10:44:11 [D] launcher Parsed request type: ping
0000|3|2022-12-07 10:44:11 [D] launcher Send pong back
0000|3|2022-12-07 10:44:11 [D] launcher Client connected at 127.0.0.1:62567
0000|3|2022-12-07 10:44:11 [D] launcher service gopkg.ilharper.com/koi/core/logger.RemoteReceiver invoked
0000|3|2022-12-07 10:44:11 [D] launcher Parsed request type: cmd
0000|3|2022-12-07 10:44:11 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:11 [D] launcher Parsed command: ps
0000|3|2022-12-07 10:44:11 [D] launcher Acquired task 1
0001|3|2022-12-07 10:44:11 [D] launcher Trigger KoiCmd ps
0000|3|2022-12-07 10:44:11 [D] launcher service *koicmd.Registry invoked
0000|3|2022-12-07 10:44:11 [D] launcher Releasing task 1
0000|3|2022-12-07 10:44:11 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:12 [D] launcher service *logger.Logger invoked
0000|3|2022-12-07 10:44:12 [D] launcher service *message.Printer invoked
0000|3|2022-12-07 10:44:12 [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-07 10:44:12 [D] launcher service *koiconfig.Config invoked
```

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/206075366-67253e04-53d7-4c8a-8c36-9930b38b756c.png)
macOS 11.7.1

**Comment by Z-fly** [comment]
我明天将尝试卸载后重新用pkg安装，如果不行再用dmg重装一次

**Comment by Z-fly** [comment]
pkg安装后
启动的日志
0000|3|2022-12-08 18:09:24 [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-08 18:09:24 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:24 [D] launcher Trigger action: run
0000|3|2022-12-08 18:09:24 [D] launcher Trigger action: run ui
0000|3|2022-12-08 18:09:24 [D] launcher service gopkg.ilharper.com/koi/app/koicli/action.RunUi invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *tray.TrayDaemon injected
0000|3|2022-12-08 18:09:24 [D] launcher service *tray.TrayDaemon invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *tray.TrayUnlocker injected
0000|3|2022-12-08 18:09:24 [D] launcher Writing tray.lock...
0000|3|2022-12-08 18:09:24 [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09:24 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:24 [D] launcher Tray ready.
0000|3|2022-12-08 18:09:25 [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09:25 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:25 [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-08 18:09:25 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-08 18:09:27 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-08 18:09:27 [D] launcher Trigger action: run daemon
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *daemonproc.DaemonProcess invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *daemonproc.DaemonProcess injected
0000|3|2022-12-08 18:09:27 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *message.Printer invoked
0000|2|2022-12-08 18:09:27 [I] launcher Starting these instances:
                        default
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-08 18:09:27 [D] launcher service gopkg.ilharper.com/koi/app/util.AppVersion invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *daemonunlk.DaemonUnlocker injected
0000|3|2022-12-08 18:09:27 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:27 [D] launcher Writing daemon.lock...
0000|3|2022-12-08 18:09:27 [D] launcher service *daemonserv.DaemonService injected
0000|3|2022-12-08 18:09:27 [D] launcher service *koicmd.Registry injected
0000|3|2022-12-08 18:09:27 [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *daemonserv.DaemonService invoked
0000|3|2022-12-08 18:09:27 [D] launcher service *http.Server injected
0000|3|2022-12-08 18:09:27 [D] launcher Serving daemon...
1000|2|
1000|2|$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
1000|2|Usage Error: Couldn't find a script named "start".
0000|2|2022-12-08 18:09:27 [W] launcher Instance default exited with: exit status 1
0000|3|2022-12-08 18:09: [D] launcher Client connected at 127.0.0.1:6
0000|3|2022-12-08 18:09: [D] launcher Parsed request type: ping
0000|3|2022-12-08 18:09: [D] launcher Send pong back
0000|3|2022-12-08 18:09: [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09: [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09: [D] launcher Client connected at 127.0.0.1:6
0000|3|2022-12-08 18:09: [D] launcher Parsed request type: ping
0000|3|2022-12-08 18:09: [D] launcher Send pong back
0000|3|2022-12-08 18:09: [D] launcher Client connected at 127.0.0.1:6
0000|3|2022-12-08 18:09: [D] launcher Parsed request type: cmd
0000|3|2022-12-08 18:09: [D] launcher service gopkg.ilharper.com/koi/core/logger.RemoteReceiver invoked0000|3|2022-12-08 18:09: [D] launcher service *logger.Logger invoked

0000|3|2022-12-08 18:09: [D] launcher Parsed command: ps
0000|3|2022-12-08 18:09: [D] launcher Acquired task 1
0000|3|2022-12-08 18:09: [D] launcher service *koicmd.Registry invoked
0001|3|2022-12-08 18:09: [D] launcher Trigger KoiCmd ps
0000|3|2022-12-08 18:09: [D] launcher Releasing task 1
0000|3|2022-12-08 18:09: [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09: [D] launcher service *message.Printer invoked
0000|3|2022-12-08 18:09: [D] launcher service *logger.Logger invoked
0000|3|2022-12-08 18:09: [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-08 18:09: [D] launcher service *koiconfig.Config invoked

**Comment by ilharp** [comment]
你正在从旧版本的 Koishi Desktop 升级。

如果这是意图的行为（希望保留旧版本的数据）：请参考 [此处的迁移指南](https://github.com/koishijs/koishi-desktop/releases/tag/v0.7.1) 解决问题。

如果这不是意图的行为（不希望保留旧版本的数据）：请卸载 Koishi Desktop，删除下列文件夹后重新安装 Koishi Desktop。

- `~/Library/Application Support/Il Harper/Koishi`
- `~/Library/Application Support/Koishi/Desktop`

**Comment by Z-fly** [comment]
删除文件夹后重装
日志
0000|3|2022-12-12 09:07: [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-12 09:07: [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-12 09:07: [D] launcher Trigger action: run
0000|3|2022-12-12 09:07: [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07: [D] launcher service gopkg.ilharper.com/koi/app/koicli/action.RunUi invoked
0000|3|2022-12-12 09:07: [D] launcher Trigger action: run ui
0000|3|2022-12-12 09:07: [D] launcher service *tray.TrayDaemon injected
0000|3|2022-12-12 09:07: [D] launcher service *tray.TrayDaemon invoked
0000|3|2022-12-12 09:07: [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07: [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07: [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07: [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-12 09:07: [D] launcher Writing tray.lock...
0000|3|2022-12-12 09:07: [D] launcher service *tray.TrayUnlocker injected
0000|3|2022-12-12 09:07: [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07: [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07: [D] launcher Tray ready.
0000|3|2022-12-12 09:07: [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07: [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07: [D] launcher service *koishell.KoiShell invoked
0000|3|2022-12-12 09:07: [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koishell.KoiShell injected
0000|3|2022-12-12 09:07:41 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher Trigger action: run daemon
0000|3|2022-12-12 09:07:41 [D] launcher service *daemonproc.DaemonProcess invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *daemonproc.DaemonProcess injected
0000|3|2022-12-12 09:07:41 [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *logger.Logger invoked
0000|2|2022-12-12 09:07:41 [I] launcher Starting these instances:
                        default
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:41 [D] launcher service gopkg.ilharper.com/koi/app/util.AppVersion invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *rpl.Receiver invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *daemonunlk.DaemonUnlocker injected
0000|3|2022-12-12 09:07:41 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:41 [D] launcher Writing daemon.lock...
0000|3|2022-12-12 09:07:41 [D] launcher service *daemonserv.DaemonService injected
0000|3|2022-12-12 09:07:41 [D] launcher service *koicmd.Registry injected
0000|3|2022-12-12 09:07:41 [D] launcher service *daemonserv.DaemonService invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:41 [D] launcher service *http.Server injected
0000|3|2022-12-12 09:07:41 [D] launcher Serving daemon...
1000|2|
1000|2|$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
1000|2|Usage Error: Couldn't find a script named "start".
0000|2|2022-12-12 09:07:42 [W] launcher Instance default exited with: exit status 1
0000|3|2022-12-12 09:07:45 [D] launcher Client connected at 127.0.0.1:5
0000|3|2022-12-12 09:07:45 [D] launcher Parsed request type: ping
0000|3|2022-12-12 09:07:45 [D] launcher Send pong back
0000|3|2022-12-12 09:07:45 [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07:45 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:45 [D] launcher Client connected at 127.0.0.1:5
0000|3|2022-12-12 09:07:45 [D] launcher Parsed request type: ping
0000|3|2022-12-12 09:07:45 [D] launcher Send pong back
0000|3|2022-12-12 09:07:45 [D] launcher Client connected at 127.0.0.1:5
0000|3|2022-12-12 09:07:45 [D] launcher service gopkg.ilharper.com/koi/core/logger.RemoteReceiver invoked0000|3|2022-12-12 09:07:45 [D] launcher Parsed command: ps

0000|3|2022-12-12 09:07:45 [D] launcher Acquired task 1
0000|3|2022-12-12 09:07:45 [D] launcher Parsed request type: cmd
0000|3|2022-12-12 09:07:45 [D] launcher service *logger.Logger invoked
0001|3|2022-12-12 09:07:45 [D] launcher Trigger KoiCmd ps
0000|3|2022-12-12 09:07:45 [D] launcher service *koicmd.Registry invoked
0000|3|2022-12-12 09:07:45 [D] launcher Releasing task 1
0000|3|2022-12-12 09:07:45 [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07:45 [D] launcher service *message.Printer invoked
0000|3|2022-12-12 09:07:45 [D] launcher service *logger.Logger invoked
0000|3|2022-12-12 09:07:45 [D] launcher service *koiconfig.Config invoked
0000|3|2022-12-12 09:07:45 [D] launcher service *koishell.KoiShell invoked

**Comment by ilharp** [comment]
你正在从旧版本的 Koishi Desktop 升级。

如果这是意图的行为（希望保留旧版本的数据）：请参考 [此处的迁移指南](https://github.com/koishijs/koishi-desktop/releases/tag/v0.7.1) 解决问题。

如果这不是意图的行为（不希望保留旧版本的数据）：请卸载 Koishi Desktop，删除下列文件夹后重新安装 Koishi Desktop。

- `~/Library/Application Support/Il Harper/Koishi`
- `~/Library/Application Support/Koishi/Desktop`

---

如果你确信删除上述文件夹后仍遇到此问题，请在这里再次回复。我们会持续跟踪此问题。

**Comment by Z-fly** [comment]
https://user-images.githubusercontent.com/10470892/207243039-695a6d68-a586-4821-ab54-bc7408860cd8.mp4

**Comment by ilharp** [comment]
你使用了错误的命令以删除上述两个文件夹。

你需要删除的两个文件夹为：

- `~/Library/Application Support/Il Harper/Koishi`
- `~/Library/Application Support/Koishi/Desktop`

以 `~/Library/Application Support/Il Harper/Koishi` 为例，你键入的命令是

```sh
sudo rm -rf ~/Library/Application Support/Il Harper/Koishi
```

该命令的含义为：在 sudo 模式下强制删除 `~/Library/Application`、`~/Support/Il` 和 `~/Harper/Koishi` 三个文件夹及其所有子树。所幸你的 Mac 上并不存在这三个文件夹，因此这条命令并未对你的电脑产生实际的伤害，你也没有因此丢失任何文件。

要删除上述两个文件夹，请运行：

```sh
sudo rm -rf ~/Library/Application\ Support/Il\ Harper/Koishi
sudo rm -rf ~/Library/Application\ Support/Koishi/Desktop
```

另请注意上述示例代码无法保证反应你所处环境的真实情况，因此也没有人可以对上述命令的安全性做出保证。要想安全地删除上述两个文件夹，请点按「访达」，点按「用户文件夹」，然后导航至「资源库 - Application Support」，最后将 `Il Harper` 和 `Koishi` 两个文件夹拖拽至「废纸篓」。

**Comment by Z-fly** [comment]
sudo rm -rf ~/Library/Application\ Support/Il\ Harper/Koishi
sudo rm -rf ~/Library/Application\ Support/Koishi/Desktop

正解。
![image](https://user-images.githubusercontent.com/10470892/207481798-1fe72073-2a57-489d-a214-ce712d36839b.png)

**Comment by YinHuoChongYin** [comment]
I have no ~/Library/Application\ Support/Il\ Harper/Koishi，what should I do

<img width="920" height="436" alt="Image" src="https://github.com/user-attachments/assets/ae185c27-6b27-4968-9c95-81feb98a16cc" />

**Comment by YinHuoChongYin** [comment]
after I remove ~/Library/Application\ Support/Koishi/Desktop， I have successful get in the koishi，thank you

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/13c8441d-5292-49de-8b27-9beb65b72d93" />

**Comment by Z-fly** [comment]
可以的
